name:       conversions
synopsis:   Injective explicit total and partial conversions
homepage:   https://github.com/mbj/conversions#readme
maintainer: Markus Schirp mbj@schirp-ds.com, Allan Lukwago <epicallan.al@gmail.com>
github:     mbj/conversions
version:    0.0.2

dependencies:
- base               > 4.12 && < 4.15
- bytestring         ^>= 0.10
- control-bool       ^>= 0.2
- devtools           ^>= 0.0.2
- exceptions         ^>= 0.10
- mtl                ^>= 2.2
- source-constraints ^>= 0.0.1
- template-haskell   ^>= 2.15
- text               ^>= 1.2
- unliftio-core      ^>= 0.1

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-local-signatures
- -Wmissing-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fhide-source-paths
- -fplugin=SourceConstraints
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- ExistentialQuantification
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- PolyKinds
- ScopedTypeVariables
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

library:
  source-dirs: src

tests:
  test:
    main: test/Test.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - conversions
