name:       conversion
synopsis:   Injective explicit total and partial conversions
homepage:   https://github.com/mbj/conversion#readme
maintainer: Markus Schirp mbj@schirp-ds.com, Allan Lukwago <epicallan.al@gmail.com>
github:     mbj/conversion
version:    0.0.2

dependencies:
- base
- bytestring
- control-bool
- devtools
- exceptions
- mtl
- source-constraints
- template-haskell
- text

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-local-signatures
- -Wmissing-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fhide-source-paths
- -fplugin=SourceConstraints
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- ExistentialQuantification
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- PolyKinds
- ScopedTypeVariables
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

library:
  source-dirs: src

tests:
  test:
    main: test/Test.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - conversion
